AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vocal-cords

  Sample SAM Template for vocal-cords

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  VoiceCordsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      # Events:
      #   CatchAll:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /prompt
      #       Method: POST
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
          - ''
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
          - ''
          - - ApplicationInsights-SAM-
            - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VoiceCordsFunction:
    Description: First Lambda Function ARN
    Value: !GetAtt VoiceCordsFunction.Arn
  VoiceCordsFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt VoiceCordsFunctionRole.Arn
  VoiceCordsFunctionUrl:
    Description: "Function URLs endpoint"
    Value: !GetAtt VoiceCordsFunctionUrl.FunctionUrl
